# Generated by Django 5.1.3 on 2025-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_full_name_patient_gender_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
