# Generated by Django 5.1.3 on 2025-06-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_token_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='center',
            new_name='center_name',
        ),
        migrations.AddField(
            model_name='token',
            name='center_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
