# Generated by Django 5.1.3 on 2025-06-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_center_token_center_name_token_center_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('center_code', 'token_number')},
        ),
    ]
