# Generated by Django 5.1.3 on 2025-06-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_token_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('patient', 'center_code', 'token_number')},
        ),
    ]
