# Generated by Django 5.1.3 on 2025-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_token_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'center_code', 'created_at'), name='unique_token_per_patient_per_center_per_day'),
        ),
    ]
