# Generated by Django 5.1.3 on 2025-06-14 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_token_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='unique_token_per_patient_per_center_per_day',
        ),
        migrations.AlterField(
            model_name='token',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('patient', 'center_code', 'token_number')},
        ),
    ]
