# Generated by Django 5.1.3 on 2025-06-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_token_unique_token_per_patient_per_center_per_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('center_code', 'token_number')},
        ),
    ]
