# Generated by Django 5.1.3 on 2025-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_token_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
