# Generated by Django 5.1.3 on 2025-06-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_token_served_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
    ]
