# Generated by Django 5.1.3 on 2025-06-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_doctor_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
