# Generated by Django 5.1.3 on 2025-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_token_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_active',
        ),
        migrations.AddField(
            model_name='token',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
